### ISSUE TITLE
security controls covered by grace-alerting

### ISSUE THREAD

**Issue by bryanlalexander** [GSA/grace-alerting#1]
If grace-alerting covers any particular NIST controls for a consumer, they should be listed and a generic statement of how it is accomplished should accompany it.

**Comment by edryan04** [comment]
Got it, I'll look and see which controls map to grace-alerting functionality and update the README Security Compliance section accordingly. I'll also add the information providing the link to the GRACE Component Control Coverage Repository (GSA/grace-ssp) and update the README there as well.

**Comment by briankfitzwater** [comment]
@edryan04 @bryanlalexander Should this issue be closed? Looks like the security controls were added to the README

**Comment by bryanlalexander** [comment]
Yes, you are correct - this was merged with [PR#4](https://github.com/GSA/grace-alerting/pull/4)
